### ISSUE TITLE
[UPDATE] Request for a 1.20.4 release

### ISSUE THREAD

**Issue by DeveloperBlue** [NimajnebEC/auto-elytra#8]
Per title

**Comment by brooke-ec** [comment]
Sorry for the delay! You should now be able to download the 1.20.4 version from [GitHub Releases](https://github.com/NimajnebEC/auto-elytra/releases/tag/v2.1.0-1.20.4) or [Modrinth](https://modrinth.com/mod/auto-elytra/version/5frttax8)!
